Select SOC_NAME AS TOP_OCCUPATIONS, 
COUNT(*) AS NUMBER_CERTIFIED_APPLICATIONS 
, (COUNT(*)*100/ (SELECT COUNT(*) 
FROM TABLE WHERE CASE_STATUS='CERTIFIED'))AS  PERCENTAGE
FROM TABLE WHERE CASE_STATUS='CERTIFIED' 
GROUP BY SOC_NAME 
Order by count(*) DESC
LIMIT 10
